### ISSUE TITLE
Simple typo, "remainin" Geometry => SurfaceArea.js

### ISSUE THREAD

**Issue by ramses0** [smspillaz/intuitive-math#6]
Simple typo, can't clone/fork/etc at the moment.  "Remainin"

https://github.com/smspillaz/intuitive-math/blob/7a03cd1e20581a19313f43cdabd9ee767c332a60/app/containers/GeometryPage/Sections/SurfaceArea.js#L183

**Comment by smspillaz** [comment]
Hey, thanks for catching! I'll fix that right now!

**Comment by smspillaz** [comment]
Closed through https://github.com/smspillaz/intuitive-math/commit/59575daf87c21bf278b491ae21b18057b6d4ac8c
